### ISSUE TITLE
fresh install -- qwen_vl_utils dependency issue

### ISSUE THREAD

**Issue by rafstahelin** [if-ai/ComfyUI-IF_LLM#5]
installed a fresh comfyui to test IF_LLM in isolation
Used the git clonoe into custom nodes. Used embedded_install.bat but IF_LLM gives me:

Traceback (most recent call last):
  File "E:\comfy\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2092, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_LLM\__init__.py", line 14, in <module>
    from .IFLLMNode import IFLLM
  File "E:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_LLM\IFLLMNode.py", line 13, in <module>
    from .send_request import send_request
  File "E:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_LLM\send_request.py", line 27, in <module>
    from .transformers_api import TransformersModelManager
  File "E:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_LLM\transformers_api.py", line 13, in <module>
    from qwen_vl_utils import process_vision_info
ModuleNotFoundError: No module named 'qwen_vl_utils'

i dont understand why IF_LLM is also not showing on manager. Only IF_AI TOOLS

**Comment by rafstahelin** [comment]
[error.txt](https://github.com/user-attachments/files/18276005/error.txt)

**Comment by rafstahelin** [comment]
I've tried following your instructions in README but can longer install fresh IF_LLM
Please advise as my current working comfy+IF_LLM is very heavy and not practical for running quick iteration tests of profiles (need to make lots of changes to profile json files which requires restarting comfy to take effect, so very impractical )
So, hopefully i can figure out how to re-install IF_LLM fresh onto a light version of comfyui. Until then, I will not be able to test profiles it seems to me
